/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'mekanik';
  static const String PLUGIN_VERSION = '1.2.2+1';
  static const String BG = 'assets/bg.jpeg';
  static const String BG5 = 'assets/bg.png';
  static const String BGABSEN = 'assets/bgabsen.png';
  static const String LOGO_AUTOBENZ2 = 'assets/logo_autobenz2.png';
  static const String LOGO_TECH = 'assets/logo_tech.png';
  static const String SOUND = 'assets/sounds/sound.mp3';
  static const String SOUNDS_BOOKING = 'assets/sounds/sounds_booking.mp3';
}
